name: Automated Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  jest:
    name: Jest ubuntu
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        id: node
        with:
          node-version: "22"
          cache: "npm" # ✅ Cache npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
