name: Automated Tests

on:
  pull_request

jobs:
  jest:
    name: Jest ubuntu
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        id: node
        with:
          node-version: 24.x
          cache: npm

      - run: npm ci

      - run: npm test
